# tagged as quay.io/luferrar/rtu-mosquitto-broker:2.0.18
FROM docker.io/eclipse-mosquitto:2.0.18

COPY mosquitto.conf.template /mosquitto/config/mosquitto.conf.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 1883 8883 9001

ENTRYPOINT ["/entrypoint.sh"]
