enrollment-service:
  authentication:
    access-token-expiry: ""
    auth-ca-file: ""
    auth-type: ""
    auth-url: ""
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwakNDQVV5Z0F3SUJBZ0lJUXF5bHMxTDR6YXN3Q2dZSUtvWkl6ajBFQXdJd0RURUxNQWtHQTFVRUF4TUMKWTJFd0hoY05NalV3TXpFNE1EZ3hNakEwV2hjTk1qWXdNekU0TURneE1qQTFXakJCTVQ4d1BRWURWUVFERXpaagpiR2xsYm5RdFpXNXliMnhzYldWdWRDMDVNV014T0RFeVlpMWxOak13TFRRMVpHSXRPVGMyTUMwelkyWTVZelEwCk9XVTNZV1F3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRYdENSRmt2T3UzY2NmQTl1aDZwc2UKT1lueFlydU5Ed2d5dk1rYlNNNzZYRjFrVmE0NDd0amxESzFiWXpRVVdrV1hnWFc1QkRYWnVJVWxJRURnbzZoVApvMkl3WURBT0JnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdJd0RBWURWUjBUCkFRSC9CQUl3QURBckJnTlZIU01FSkRBaWdDQnRSckFiNm0xdU4yVFRId0xRVnJwN0xBYVYzWXUxbGhpclRvUWMKV3pxOVl6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQWVlRUlJZ1IzanNOcXZRcitqYXN2Um9GcTc0Q1JsdHRjTwoxMVdZbnJ4cjNRSWhBSmQ0T1BzR1RWelZ2bUwzT3dsWTVsKzdHOFVQeWhvWC9qa0FnWW95VU1CcgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-id: ""
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxZZk1GWER4TGRpUWxvWDAxUGFoQ0VLMTNNOXRQV0pteVRpRlNUM24wTkpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMTdRa1JaTHpydDNISHdQYm9lcWJIam1KOFdLN2pROElNcnpKRzBqTytseGRaRld1T083WQo1UXl0VzJNMEZGcEZsNEYxdVFRMTJiaUZKU0JBNEtPb1V3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  enrollment-ui-endpoint: http://192.168.1.48.nip.io:9000
  service:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqRENDQVRHZ0F3SUJBZ0lJYWY5OEg1eDhlOFF3Q2dZSUtvWkl6ajBFQXdJd0RURUxNQWtHQTFVRUF4TUMKWTJFd0hoY05NalV3TXpFM01UVXdNVFUxV2hjTk16VXdNekUxTVRVd01UVTJXakFOTVFzd0NRWURWUVFERXdKagpZVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSjIrdFp2eHBDUnNNcVh0d0NSUEdFQ0tzdnMzCm91b2xMSW9meis5eFdnUS9iY3ozV2ZvYytLMlFyZE1MR1NSVXJqcjBrZGw0SDBnckRKeVNZUzd0c0phamV6QjUKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQ2tHQTFVZERnUWlCQ0J0UnJBYgo2bTF1TjJUVEh3TFFWcnA3TEFhVjNZdTFsaGlyVG9RY1d6cTlZekFyQmdOVkhTTUVKREFpZ0NCdFJyQWI2bTF1Ck4yVFRId0xRVnJwN0xBYVYzWXUxbGhpclRvUWNXenE5WXpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTBNOGgKYUhKYXowMXdRRUxTbERsNWswbllNeUhoSnJhbzFkenFBbnJCUUxrQ0lRRGhxbHBaS1JhbFNYSDgzM3hLb0pYNApUOG1xcFUxQVIxbFV6UHFBRGRwR2F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://agent-api.192.168.1.48.nip.io:7443/
management-service:
  authentication:
    access-token-expiry: ""
    auth-ca-file: ""
    auth-type: ""
    auth-url: ""
    client-id: ""
  service:
    server: ""
