enrollment-service:
  authentication:
    access-token-expiry: ""
    auth-ca-file: ""
    auth-type: ""
    auth-url: ""
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwakNDQVV5Z0F3SUJBZ0lJZjNFc2trazlWaEl3Q2dZSUtvWkl6ajBFQXdJd0RURUxNQWtHQTFVRUF4TUMKWTJFd0hoY05NalV3TXpBM01URTBOREE0V2hjTk1qWXdNekEzTVRFME5EQTVXakJCTVQ4d1BRWURWUVFERXpaagpiR2xsYm5RdFpXNXliMnhzYldWdWRDMHlabVE1WVdSaVlpMDJOVFF3TFRSaE5HTXRPVGt3TWkwNE5EVmpOV0UwCllUQmpZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFlekpYdUZkV0YvdVVFQ3IzdW9pQWIKMVNGR2dvZGtQNkNMcE1hem1sMDI4WlprWStCTG1NWFFJOFlnYllWZnJtSXdZM3ZyV2NpakhDRS9uSjBsbzRaZApvMkl3WURBT0JnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdJd0RBWURWUjBUCkFRSC9CQUl3QURBckJnTlZIU01FSkRBaWdDREJvVnlNTHFNZEM1cUtuWXFYTGdmczhzSDZGczU2YmhwczdLalYKUFlOSWhqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUErL3NiZWs5Tnkwdzl0TTI4M1NsbGlBc2ZmdTdFRi8vSQpkTGdqeFU5MnBuWUNJSFNpai9mYU8wTnFvek1PNnFuV3B5ZUx6Nkd5Ritza0NzMU96bzJiZzVkTwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-id: ""
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUloNWNhbVpTWG11amJqLzJ0c2NTaFBSQzFjZ0ZjQjRFZlpqN0JkMjNESklvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSHN5VjdoWFZoZjdsQkFxOTdxSWdHOVVoUm9LSFpEK2dpNlRHczVwZE52R1daR1BnUzVqRgowQ1BHSUcyRlg2NWlNR043NjFuSW94d2hQNXlkSmFPR1hRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  enrollment-ui-endpoint: http://192.168.1.48.nip.io:9000
  service:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRHZ0F3SUJBZ0lJUnlkTDBSbkxFdG93Q2dZSUtvWkl6ajBFQXdJd0RURUxNQWtHQTFVRUF4TUMKWTJFd0hoY05NalV3TXpBMU1UY3hOekExV2hjTk16VXdNekF6TVRjeE56QTJXakFOTVFzd0NRWURWUVFERXdKagpZVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTlViaU9idmtOYnUyZzdLL3h2WXpPMVhFaXhiCkFPRzUvaWo1d2VMdTZQSzlLNXhRTnhSQlFTazZqT21mNlY5ZktnQ2hzOVoxcVhmeE44dVJMWnVFYlNtamV6QjUKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQ2tHQTFVZERnUWlCQ0RCb1Z5TQpMcU1kQzVxS25ZcVhMZ2ZzOHNINkZzNTZiaHBzN0tqVlBZTkloakFyQmdOVkhTTUVKREFpZ0NEQm9WeU1McU1kCkM1cUtuWXFYTGdmczhzSDZGczU2YmhwczdLalZQWU5JaGpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlCampGWGgKOU5uUHpnUWd4V01CWFRIV3FPNTFSbUU3ejdRNlBpTVB4WmtTNGdJaEFOczJPKzdLeldjdnFzemNqSVoweXYwWgpkLzlGRTFHVE1LM21sM05FM1BaegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://agent-api.192.168.1.48.nip.io:7443/
management-service:
  authentication:
    access-token-expiry: ""
    auth-ca-file: ""
    auth-type: ""
    auth-url: ""
    client-id: ""
  service:
    server: ""
