FROM osbuild.lmf.openshift.es:5000/gitea/microshift-4.18-bootc:latest
ADD etc etc
RUN dnf install -y opentelemetry-collector && dnf clean all
ADD opentelemetry-collector.service /usr/lib/systemd/system/
RUN systemctl enable opentelemetry-collector.service

